### PR TITLE
changed sensor type to Sensor.TYPE_GYROSCOPE

### PR DESCRIPTION
**Pull request by sofifather**
Changed sensor type.For now important to set screen orientation before use this class cause calculations depends on gyroscope axises and must be inverted while activity is in landscape orientation.By default it is in portrait.

### CODE REVIEW

**Comment by protyposis** [comment]
Did you close this on purpose?

**Comment by sofifather** [comment]
Yes.There need more attention to details.and I am found that calculations not precise.If user move head fast then initial point of view lose and needs to be reset and it is not friendly for users

**Comment by protyposis** [comment]
Ok thank you! I've been thinking about this and I guess the problem that you have is that the gyroscope only gives you relative rotation data and the error accumulates over time. It might make more sense to use a sensor that provides absolute values, like the [magnetometer/compass](https://developer.android.com/guide/topics/sensors/sensors_position.html#sensors-pos-orient)!?

**Comment by sofifather** [comment]
Of course proposed sensor data more precisely cause it has absolute position.Thank you for help.

**Pull request closed without merging**
